import { Brain } from "@/types"

export const BRAINS: Brain[] = [

  // ── 🧠 INTELLIGENCE & RESEARCH ─────────────────────────────────

  {
    id: "billion-dollar-idea-finder",
    name: "Billion Dollar Idea Finder",
    description: "Scrapes Product Hunt, HackerNews, Twitter, Reddit and Google Trends in real time. Finds market gaps, emerging behaviours and underserved pain points. Returns 10 ranked startup ideas with market size, competition level and why now.",
    author: "flowos_team",
    category: "Research & Intelligence",
    icon: "💡",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 28400,
    rating: 4.9,
    reviews: 980,
    estimatedTime: "~15 min",
    tags: ["startup", "ideas", "trends", "research", "founder"],
    inputs: [
      { key: "industry", label: "Your Industry / Domain", placeholder: "FinTech, HealthTech, EdTech, anything", type: "text", required: false },
      { key: "region", label: "Target Market", placeholder: "India, Global, Southeast Asia", type: "text", required: false },
      { key: "stage", label: "Your Stage", placeholder: "Idea, MVP, Funded", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.producthunt.com/topics/developer-tools" },
      { id: "s2", action: "ai_handle", instruction: "Scrape top trending products launched this week. Extract names, descriptions, upvotes, and problems they solve." },
      { id: "s3", action: "navigate", url: "https://news.ycombinator.com/ask" },
      { id: "s4", action: "ai_handle", instruction: "Find all 'Ask HN: Who is hiring' and 'Show HN' posts. Identify patterns in what problems founders are solving." },
      { id: "s5", action: "navigate", url: "https://trends.google.com/trends/trendingsearches/daily?geo=IN" },
      { id: "s6", action: "ai_handle", instruction: "Extract today's top trending searches in the target region." },
      { id: "s7", action: "navigate", url: "https://www.reddit.com/r/startups/top/?t=week" },
      { id: "s8", action: "ai_handle", instruction: "Find posts about problems people are desperately trying to solve. Extract pain points." },
      { id: "s9", action: "ai_handle", instruction: "Synthesise all research. Generate 10 ranked startup ideas with: idea name, problem, solution, target user, market size estimate, competition level (low/medium/high), why this idea is timely right now, and a one-line pitch. Format as structured JSON and save to /tmp/extract.json." },
      { id: "s10", action: "extract" },
      { id: "s11", action: "notify", value: "Your 10 billion dollar ideas are ready!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "market-research-report",
    name: "Full Market Research Report",
    description: "Give it any market or idea and it produces a comprehensive 10-page research report: market size, top players, pricing analysis, customer complaints, whitespace opportunities, and entry strategy. Exported as PDF.",
    author: "flowos_team",
    category: "Research & Intelligence",
    icon: "📊",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 19200,
    rating: 4.8,
    reviews: 640,
    estimatedTime: "~20 min",
    tags: ["market research", "competitor analysis", "report", "founder", "investor"],
    inputs: [
      { key: "market", label: "Market or Idea", placeholder: "AI-powered HR software for Indian SMBs", type: "text", required: true },
      { key: "depth", label: "Report Depth", placeholder: "Overview / Deep Dive", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.google.com/search?q={{market}}+market+size+2025+India" },
      { id: "s2", action: "ai_handle", instruction: "Extract market size data, growth rates, and key statistics from search results." },
      { id: "s3", action: "navigate", url: "https://www.g2.com/search#query={{market}}" },
      { id: "s4", action: "ai_handle", instruction: "Find top 5 competitors. For each: extract name, pricing, top 3 features, top 3 complaints from reviews." },
      { id: "s5", action: "navigate", url: "https://www.reddit.com/search/?q={{market}}+problem&sort=top" },
      { id: "s6", action: "ai_handle", instruction: "Find recurring customer complaints and unmet needs in this market." },
      { id: "s7", action: "ai_handle", instruction: "Compile everything into a structured market research report with sections: Executive Summary, Market Size, Key Players, Pricing Analysis, Customer Pain Points, Whitespace Opportunities, Recommended Entry Strategy. Save as JSON to /tmp/extract.json." },
      { id: "s8", action: "extract" },
      { id: "s9", action: "notify", value: "Your market research report is ready to download." },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "competitor-deep-dive",
    name: "Competitor Deep Dive",
    description: "Analyses any competitor in depth — their pricing, features, SEO strategy, tech stack, hiring patterns, recent news, customer sentiment and weaknesses. Gives you an exact playbook to beat them.",
    author: "flowos_team",
    category: "Research & Intelligence",
    icon: "🔬",
    version: "1.0.0",
    verified: true,
    trending: false,
    featured: false,
    installs: 14300,
    rating: 4.7,
    reviews: 420,
    estimatedTime: "~25 min",
    tags: ["competitor", "analysis", "strategy", "founder"],
    inputs: [
      { key: "competitor_url", label: "Competitor Website", placeholder: "https://competitor.com", type: "url", required: true },
      { key: "your_product", label: "Your Product / Idea", placeholder: "What you're building", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "{{competitor_url}}" },
      { id: "s2", action: "ai_handle", instruction: "Extract: company description, core features, pricing tiers, target customer, value proposition." },
      { id: "s3", action: "navigate", url: "https://www.similarweb.com/website/{{competitor_url}}" },
      { id: "s4", action: "ai_handle", instruction: "Extract traffic stats, top traffic sources, top countries, engagement metrics." },
      { id: "s5", action: "navigate", url: "https://www.linkedin.com/company/{{competitor_url}}/jobs" },
      { id: "s6", action: "ai_handle", instruction: "Analyse open jobs to understand what they're investing in — which teams are growing, what tech they use." },
      { id: "s7", action: "navigate", url: "https://www.g2.com/search#query={{competitor_url}}" },
      { id: "s8", action: "ai_handle", instruction: "Extract top positive reviews (what users love) and top negative reviews (what users hate)." },
      { id: "s9", action: "ai_handle", instruction: "Synthesise a competitor playbook: their strengths, weaknesses, opportunities to beat them, and 5 concrete tactics to take their customers. Save to /tmp/extract.json." },
      { id: "s10", action: "extract" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ── 📊 BUSINESS & FOUNDER TOOLS ────────────────────────────────

  {
    id: "pitch-deck-builder",
    name: "Pitch Deck Builder",
    description: "Generates a complete investor-ready pitch deck for your startup. Researches your market automatically, writes all 12 slides, and exports a beautiful PowerPoint. Used by founders to raise pre-seed and seed rounds.",
    author: "flowos_team",
    category: "Business & Finance",
    icon: "🚀",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 32100,
    rating: 4.9,
    reviews: 1100,
    estimatedTime: "~20 min",
    tags: ["pitch deck", "investor", "fundraising", "founder", "startup"],
    inputs: [
      { key: "startup_name", label: "Startup Name", placeholder: "FlowOS", type: "text", required: true },
      { key: "one_liner", label: "One Line Description", placeholder: "Jarvis for India — AI that gets things done", type: "text", required: true },
      { key: "problem", label: "Problem You Solve", placeholder: "People waste hours on repetitive internet tasks", type: "textarea", required: true },
      { key: "target_market", label: "Target Market", placeholder: "Indian job seekers, founders, freelancers", type: "text", required: true },
      { key: "traction", label: "Current Traction", placeholder: "500 users, ₹2L MRR, 3 enterprise pilots", type: "text", required: false },
      { key: "ask", label: "Funding Ask", placeholder: "$500K pre-seed", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.google.com/search?q={{target_market}}+market+size+India+2025" },
      { id: "s2", action: "ai_handle", instruction: "Extract market size data and growth projections for this target market." },
      { id: "s3", action: "navigate", url: "https://news.ycombinator.com/search?q={{startup_name}}" },
      { id: "s4", action: "ai_handle", instruction: "Research any relevant news, competitors, or trends related to this startup idea." },
      { id: "s5", action: "ai_handle", instruction: "Generate a complete 12-slide pitch deck structure: 1-Cover, 2-Problem, 3-Solution, 4-Product Demo, 5-Market Size (TAM/SAM/SOM), 6-Business Model, 7-Traction, 8-Competition, 9-Go-to-Market, 10-Team, 11-Financials, 12-The Ask. For each slide write: title, 3-5 bullet points, key stat or visual suggestion. Use the provided startup details and researched market data. Save complete deck content to /tmp/extract.json." },
      { id: "s6", action: "extract" },
      { id: "s7", action: "notify", value: "Your pitch deck is ready! Download and open in PowerPoint or Google Slides." },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "startup-event-booker",
    name: "Startup Event Booker",
    description: "Finds and registers you for the best startup events, demo days, accelerator programmes and networking events happening this month — in your city or online. Never miss a Nasscom, YC, or TiE event again.",
    author: "flowos_team",
    category: "Business & Finance",
    icon: "🎪",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 18700,
    rating: 4.7,
    reviews: 560,
    estimatedTime: "~30 min",
    tags: ["events", "networking", "startup", "accelerator", "india"],
    inputs: [
      { key: "city", label: "Your City", placeholder: "Mumbai, Bangalore, Delhi, or Online", type: "text", required: true },
      { key: "stage", label: "Startup Stage", placeholder: "Idea, Pre-seed, Seed, Series A", type: "text", required: true },
      { key: "industry", label: "Industry", placeholder: "FinTech, SaaS, HealthTech", type: "text", required: false },
      { key: "email", label: "Registration Email", placeholder: "you@startup.com", type: "text", required: true, vaultKey: "email" },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.meetup.com/find/?keywords=startup+{{industry}}&location={{city}}" },
      { id: "s2", action: "ai_handle", instruction: "Find all upcoming startup events in the city. Extract: event name, date, description, registration link, cost." },
      { id: "s3", action: "navigate", url: "https://www.eventbrite.com/d/india--{{city}}/startup-events/" },
      { id: "s4", action: "ai_handle", instruction: "Find relevant startup events. Add to the list." },
      { id: "s5", action: "navigate", url: "https://nasscom.in/events" },
      { id: "s6", action: "ai_handle", instruction: "Find upcoming NASSCOM events relevant to the startup stage and industry." },
      { id: "s7", action: "navigate", url: "https://www.linkedin.com/search/results/events/?keywords=startup+{{city}}" },
      { id: "s8", action: "ai_handle", instruction: "Find LinkedIn events for startups in this location." },
      { id: "s9", action: "ai_handle", instruction: "Rank all found events by relevance to the user's stage and industry. Register for the top 3 free events using the provided email. Save full event list to /tmp/extract.json." },
      { id: "s10", action: "extract" },
      { id: "s11", action: "notify", value: "Found and registered for top startup events in your area!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "investor-finder",
    name: "Investor Finder & Outreach",
    description: "Finds the most relevant angel investors and VCs for your startup based on their portfolio, cheque size and thesis. Drafts personalised cold emails for each. All you do is hit send.",
    author: "flowos_team",
    category: "Business & Finance",
    icon: "💰",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: false,
    installs: 22400,
    rating: 4.8,
    reviews: 780,
    estimatedTime: "~25 min",
    tags: ["investor", "fundraising", "angel", "VC", "outreach"],
    inputs: [
      { key: "startup_description", label: "Startup Description", placeholder: "We build AI automation for Indian SMBs", type: "textarea", required: true },
      { key: "stage", label: "Stage & Ask", placeholder: "Pre-seed, raising $300K", type: "text", required: true },
      { key: "industry", label: "Industry", placeholder: "SaaS / AI / FinTech", type: "text", required: true },
      { key: "founder_name", label: "Your Name", placeholder: "Ambar Singh", type: "text", required: true },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.angellist.com/investors" },
      { id: "s2", action: "ai_handle", instruction: "Search for investors who invest in {{industry}} at {{stage}}. Extract: name, firm, portfolio companies, investment thesis, contact info." },
      { id: "s3", action: "navigate", url: "https://www.tracxn.com/d/investor-lists/top-angel-investors-in-india" },
      { id: "s4", action: "ai_handle", instruction: "Find top Indian angel investors relevant to this startup. Add to investor list." },
      { id: "s5", action: "navigate", url: "https://thecatalyst.org.in/investors" },
      { id: "s6", action: "ai_handle", instruction: "Find relevant Indian VCs and their investment focus." },
      { id: "s7", action: "ai_handle", instruction: "For each relevant investor generate a personalised cold email that: references a specific portfolio company of theirs, connects it to our startup, clearly states the ask. Save investor list + emails to /tmp/extract.json." },
      { id: "s8", action: "extract" },
      { id: "s9", action: "notify", value: "Found 20+ investors with personalised emails ready to send!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "grant-finder-india",
    name: "India Grant & Scheme Finder",
    description: "Finds every government grant, scheme, and funding programme your startup qualifies for — Startup India, DPIIT, SIDBI, state schemes and more. Fills and submits applications automatically.",
    author: "flowos_team",
    category: "Business & Finance",
    icon: "🏛️",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: false,
    installs: 31200,
    rating: 4.6,
    reviews: 890,
    estimatedTime: "~40 min",
    tags: ["grants", "india", "startup india", "DPIIT", "government", "funding"],
    inputs: [
      { key: "startup_name", label: "Startup Name", placeholder: "FlowOS Technologies", type: "text", required: true },
      { key: "industry", label: "Industry", placeholder: "AI / SaaS / HealthTech", type: "text", required: true },
      { key: "state", label: "Registered State", placeholder: "Maharashtra", type: "text", required: true },
      { key: "stage", label: "Stage", placeholder: "Ideation / Validation / Early Traction", type: "text", required: true },
      { key: "cin", label: "CIN / GSTIN (if registered)", placeholder: "Optional", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.startupindia.gov.in/content/sih/en/government-schemes.html" },
      { id: "s2", action: "ai_handle", instruction: "Find all schemes matching the startup's industry, stage and state. Extract eligibility criteria, benefits, and application links." },
      { id: "s3", action: "navigate", url: "https://seedfund.startupindia.gov.in" },
      { id: "s4", action: "ai_handle", instruction: "Check eligibility for Startup India Seed Fund. Extract requirements and deadline." },
      { id: "s5", action: "navigate", url: "https://www.sidbi.in/en/startup-mitra" },
      { id: "s6", action: "ai_handle", instruction: "Find SIDBI schemes matching the startup profile." },
      { id: "s7", action: "ai_handle", instruction: "Compile a ranked list of all applicable grants and schemes with: name, benefit amount, eligibility match score, application deadline, direct link, and step-by-step application guide. Save to /tmp/extract.json." },
      { id: "s8", action: "extract" },
      { id: "s9", action: "notify", value: "Found government schemes you qualify for — with application guides!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ── 🎯 CAREER & PROFESSIONALS ───────────────────────────────────

  {
    id: "resume-optimizer",
    name: "Resume ATS Optimizer",
    description: "Reads your resume and a job description. Rewrites your resume to pass ATS filters, match keywords, and stand out to recruiters. Gives you a match score before and after.",
    author: "flowos_team",
    category: "Jobs & Career",
    icon: "📄",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 44300,
    rating: 4.9,
    reviews: 1560,
    estimatedTime: "~5 min",
    tags: ["resume", "ATS", "jobs", "career", "interview"],
    inputs: [
      { key: "resume_url", label: "Resume Link (Google Drive / PDF)", placeholder: "https://drive.google.com/...", type: "url", required: true, vaultKey: "resume_url" },
      { key: "job_url", label: "Job Posting URL", placeholder: "https://linkedin.com/jobs/...", type: "url", required: true },
      { key: "target_role", label: "Target Role", placeholder: "Senior Product Manager", type: "text", required: true },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "{{job_url}}" },
      { id: "s2", action: "ai_handle", instruction: "Extract the complete job description, required skills, preferred qualifications, and key responsibilities." },
      { id: "s3", action: "navigate", url: "{{resume_url}}" },
      { id: "s4", action: "ai_handle", instruction: "Extract the complete resume content." },
      { id: "s5", action: "ai_handle", instruction: "Analyse ATS match score between resume and JD. Then rewrite the resume to: add missing keywords naturally, strengthen bullet points with metrics, reorder sections for this role. Output: original score, new score, rewritten resume in plain text, and list of changes made. Save to /tmp/extract.json." },
      { id: "s6", action: "extract" },
      { id: "s7", action: "notify", value: "Your ATS-optimised resume is ready!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "interview-prep",
    name: "Interview Prep Coach",
    description: "Give it a company name and role. It researches the company deeply, generates the 20 most likely interview questions with model answers tailored to you, and gives you a prep plan.",
    author: "flowos_team",
    category: "Jobs & Career",
    icon: "🎯",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: false,
    installs: 38900,
    rating: 4.8,
    reviews: 1290,
    estimatedTime: "~10 min",
    tags: ["interview", "preparation", "career", "jobs"],
    inputs: [
      { key: "company", label: "Company Name", placeholder: "Google, Razorpay, Zepto", type: "text", required: true },
      { key: "role", label: "Role", placeholder: "Software Engineer, Product Manager", type: "text", required: true },
      { key: "experience", label: "Years of Experience", placeholder: "3", type: "number", required: true },
      { key: "resume_url", label: "Resume (optional)", placeholder: "https://drive.google.com/...", type: "url", required: false, vaultKey: "resume_url" },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.glassdoor.co.in/Interview/{{company}}-Interview-Questions-E{{company}}.htm" },
      { id: "s2", action: "ai_handle", instruction: "Extract real interview questions asked at this company for this role. Note patterns and frequently asked topics." },
      { id: "s3", action: "navigate", url: "https://www.linkedin.com/company/{{company}}" },
      { id: "s4", action: "ai_handle", instruction: "Extract company mission, recent news, products, culture, tech stack." },
      { id: "s5", action: "navigate", url: "https://www.google.com/search?q={{company}}+engineering+blog+{{role}}" },
      { id: "s6", action: "ai_handle", instruction: "Find any public engineering or product blog posts from this company." },
      { id: "s7", action: "ai_handle", instruction: "Generate: company overview summary, 20 likely interview questions (mix of technical, behavioural, case), model answer for each, 5 smart questions to ask the interviewer, 3-day prep plan. Save to /tmp/extract.json." },
      { id: "s8", action: "extract" },
      { id: "s9", action: "notify", value: "Your interview prep pack is ready — good luck!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "freelance-client-finder",
    name: "Freelance Client Finder",
    description: "Finds active clients looking for your exact skill on Upwork, LinkedIn, Reddit and Twitter. Drafts personalised proposals for each. Sends applications automatically.",
    author: "flowos_team",
    category: "Jobs & Career",
    icon: "💻",
    version: "1.0.0",
    verified: true,
    trending: false,
    featured: false,
    installs: 17600,
    rating: 4.6,
    reviews: 490,
    estimatedTime: "~45 min",
    tags: ["freelance", "clients", "upwork", "linkedin", "proposal"],
    inputs: [
      { key: "skill", label: "Your Skill", placeholder: "React Developer, UI/UX Designer, Copywriter", type: "text", required: true },
      { key: "rate", label: "Hourly Rate", placeholder: "$25/hr", type: "text", required: true },
      { key: "portfolio_url", label: "Portfolio URL", placeholder: "https://yourportfolio.com", type: "url", required: false },
      { key: "bio", label: "Short Bio", placeholder: "5 years building React apps for SaaS companies", type: "textarea", required: true },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.upwork.com/search/jobs/?q={{skill}}&sort=recency" },
      { id: "s2", action: "ai_handle", instruction: "Find the 10 most relevant recently posted jobs. Extract: title, budget, description, client rating, required skills." },
      { id: "s3", action: "navigate", url: "https://www.reddit.com/r/forhire/search/?q={{skill}}&sort=new" },
      { id: "s4", action: "ai_handle", instruction: "Find hiring posts for this skill. Add to opportunities list." },
      { id: "s5", action: "navigate", url: "https://twitter.com/search?q=%22looking+for+{{skill}}%22&f=live" },
      { id: "s6", action: "ai_handle", instruction: "Find tweets from people actively looking for this skill." },
      { id: "s7", action: "ai_handle", instruction: "For each opportunity write a personalised proposal that: references specifics from their job post, highlights relevant experience from the bio, includes a concrete next step. Save all opportunities and proposals to /tmp/extract.json." },
      { id: "s8", action: "extract" },
      { id: "s9", action: "notify", value: "Found clients and drafted proposals — ready to send!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ── 📱 CONTENT & MARKETING ──────────────────────────────────────

  {
    id: "linkedin-content-engine",
    name: "LinkedIn Content Engine",
    description: "Researches trending topics in your industry, writes 7 high-engagement LinkedIn posts for the whole week, and schedules them. Includes hooks, storytelling, and CTAs optimised for the algorithm.",
    author: "flowos_team",
    category: "Social Media",
    icon: "✍️",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 29800,
    rating: 4.8,
    reviews: 940,
    estimatedTime: "~15 min",
    tags: ["linkedin", "content", "marketing", "personal brand", "posts"],
    inputs: [
      { key: "industry", label: "Your Industry", placeholder: "AI, FinTech, Marketing", type: "text", required: true },
      { key: "role", label: "Your Role", placeholder: "Founder, Developer, Designer", type: "text", required: true },
      { key: "tone", label: "Tone", placeholder: "Inspirational, Educational, Contrarian", type: "text", required: false },
      { key: "linkedin_cookie", label: "LinkedIn Session Cookie", placeholder: "Paste your li_at cookie", type: "password", required: false, vaultKey: "linkedin_cookie" },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.linkedin.com/feed/" },
      { id: "s2", action: "ai_handle", instruction: "Find the top 5 trending topics and post formats in {{industry}} this week." },
      { id: "s3", action: "navigate", url: "https://twitter.com/search?q={{industry}}+insight&f=live" },
      { id: "s4", action: "ai_handle", instruction: "Find viral insights and angles being discussed in this industry." },
      { id: "s5", action: "ai_handle", instruction: "Write 7 LinkedIn posts for the week. Each post must have: a scroll-stopping first line, 150-300 words, personal insight or story angle, 3 key takeaways, strong CTA, 5 relevant hashtags. Vary formats: story, list, hot take, how-to, case study. Save all 7 posts with suggested posting times to /tmp/extract.json." },
      { id: "s6", action: "extract" },
      { id: "s7", action: "notify", value: "Your week of LinkedIn content is ready!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "viral-content-idea-machine",
    name: "Viral Content Idea Machine",
    description: "Analyses what content is going viral in your niche across YouTube, Instagram, Twitter and Reddit this week. Gives you 30 proven content ideas with titles, formats, hooks and why they'll work for your audience.",
    author: "flowos_team",
    category: "Social Media",
    icon: "🔥",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: false,
    installs: 23400,
    rating: 4.7,
    reviews: 720,
    estimatedTime: "~20 min",
    tags: ["viral", "content", "youtube", "instagram", "ideas"],
    inputs: [
      { key: "niche", label: "Your Niche", placeholder: "Personal Finance, Tech, Fitness, Cooking", type: "text", required: true },
      { key: "platform", label: "Primary Platform", placeholder: "Instagram, YouTube, Twitter", type: "text", required: true },
      { key: "audience", label: "Target Audience", placeholder: "Indian college students, working professionals", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.youtube.com/results?search_query={{niche}}&sp=CAISBAgBEAE%3D" },
      { id: "s2", action: "ai_handle", instruction: "Find videos posted this week with highest view counts in this niche. Extract: titles, view counts, thumbnails descriptions, why they worked." },
      { id: "s3", action: "navigate", url: "https://www.reddit.com/r/{{niche}}/top/?t=week" },
      { id: "s4", action: "ai_handle", instruction: "Find top posts this week. Extract formats, topics, engagement patterns." },
      { id: "s5", action: "navigate", url: "https://twitter.com/search?q={{niche}}&f=live&src=typed_query" },
      { id: "s6", action: "ai_handle", instruction: "Find trending discussions and viral tweets in this niche." },
      { id: "s7", action: "ai_handle", instruction: "Generate 30 content ideas. For each: title/hook, format (reel/carousel/video/thread), why it will go viral, best time to post, estimated engagement potential. Rank by viral potential. Save to /tmp/extract.json." },
      { id: "s8", action: "extract" },
      { id: "s9", action: "notify", value: "30 viral content ideas ready — start creating!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ── 🏥 PROFESSION-SPECIFIC ──────────────────────────────────────

  {
    id: "doctor-patient-research",
    name: "Medical Research Assistant",
    description: "For doctors and medical professionals. Researches latest treatment protocols, drug interactions, clinical trials and medical literature for any condition. Summarises findings in clinical language.",
    author: "flowos_team",
    category: "Healthcare",
    icon: "🩺",
    version: "1.0.0",
    verified: true,
    trending: false,
    featured: false,
    installs: 8900,
    rating: 4.8,
    reviews: 280,
    estimatedTime: "~10 min",
    tags: ["medical", "research", "doctor", "clinical", "healthcare"],
    inputs: [
      { key: "condition", label: "Condition / Drug / Topic", placeholder: "Type 2 Diabetes management 2025", type: "text", required: true },
      { key: "focus", label: "Research Focus", placeholder: "Latest treatment guidelines, drug interactions, clinical trials", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://pubmed.ncbi.nlm.nih.gov/?term={{condition}}&filter=dates.2024%2F1%2F1-3000%2F1%2F1&sort=date" },
      { id: "s2", action: "ai_handle", instruction: "Extract the 5 most recent and relevant research papers. For each: title, authors, year, key findings, clinical implications." },
      { id: "s3", action: "navigate", url: "https://www.uptodate.com/contents/search?search={{condition}}" },
      { id: "s4", action: "ai_handle", instruction: "Find current treatment guidelines and protocols." },
      { id: "s5", action: "navigate", url: "https://clinicaltrials.gov/search?cond={{condition}}&status=RECRUITING" },
      { id: "s6", action: "ai_handle", instruction: "Find active clinical trials the patient might qualify for." },
      { id: "s7", action: "ai_handle", instruction: "Write a comprehensive clinical summary: current best-practice treatment, recent research findings, relevant trials, drug considerations. Use clinical language. Save to /tmp/extract.json." },
      { id: "s8", action: "extract" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "lawyer-case-researcher",
    name: "Legal Case Researcher",
    description: "For lawyers and law students. Finds relevant case precedents, recent judgements, and legal arguments for any matter. Searches Indian Kanoon, Supreme Court records and legal databases.",
    author: "flowos_team",
    category: "Legal",
    icon: "⚖️",
    version: "1.0.0",
    verified: true,
    trending: false,
    featured: false,
    installs: 11200,
    rating: 4.7,
    reviews: 340,
    estimatedTime: "~15 min",
    tags: ["legal", "lawyer", "case law", "India", "judgement"],
    inputs: [
      { key: "matter", label: "Legal Matter", placeholder: "Wrongful termination under Indian labour law", type: "textarea", required: true },
      { key: "jurisdiction", label: "Jurisdiction", placeholder: "Supreme Court, Bombay High Court", type: "text", required: false },
      { key: "year_range", label: "Year Range", placeholder: "2020-2025", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://indiankanoon.org/search/?formInput={{matter}}" },
      { id: "s2", action: "ai_handle", instruction: "Find the 10 most relevant cases. For each extract: case name, court, year, key ruling, legal principle established." },
      { id: "s3", action: "navigate", url: "https://main.sci.gov.in/judgments" },
      { id: "s4", action: "ai_handle", instruction: "Find recent Supreme Court judgements on this matter." },
      { id: "s5", action: "ai_handle", instruction: "Compile a legal research memo: summary of legal position, top 10 precedents with citations, key arguments for and against, recent trend in judicial interpretation. Save to /tmp/extract.json." },
      { id: "s6", action: "extract" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  {
    id: "teacher-lesson-planner",
    name: "Teacher Lesson Planner",
    description: "Creates complete lesson plans, worksheets, quizzes, and teaching materials for any subject and grade level. Aligned to CBSE, ICSE or any curriculum. Saves teachers 4+ hours per week.",
    author: "flowos_team",
    category: "Education",
    icon: "📚",
    version: "1.0.0",
    verified: true,
    trending: false,
    featured: false,
    installs: 26700,
    rating: 4.9,
    reviews: 890,
    estimatedTime: "~10 min",
    tags: ["teacher", "education", "lesson plan", "CBSE", "worksheet"],
    inputs: [
      { key: "subject", label: "Subject", placeholder: "Mathematics, Physics, History", type: "text", required: true },
      { key: "topic", label: "Topic", placeholder: "Quadratic Equations, World War II", type: "text", required: true },
      { key: "grade", label: "Grade / Class", placeholder: "Class 10, Grade 8", type: "text", required: true },
      { key: "duration", label: "Class Duration", placeholder: "45 minutes", type: "text", required: false },
      { key: "curriculum", label: "Curriculum", placeholder: "CBSE, ICSE, State Board", type: "text", required: false },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.google.com/search?q={{curriculum}}+{{subject}}+{{topic}}+{{grade}}+syllabus+learning+objectives" },
      { id: "s2", action: "ai_handle", instruction: "Extract official learning objectives and curriculum requirements for this topic." },
      { id: "s3", action: "navigate", url: "https://www.khanacademy.org/search?page_search_query={{topic}}" },
      { id: "s4", action: "ai_handle", instruction: "Find relevant explanations, examples and approaches for teaching this topic." },
      { id: "s5", action: "ai_handle", instruction: "Create complete teaching materials: 1) Lesson plan with timing, 2) Student worksheet with 10 practice problems, 3) 15-question quiz with answer key, 4) 3 real-world examples, 5) Common misconceptions and how to address them, 6) Extension activities for advanced students. Save to /tmp/extract.json." },
      { id: "s6", action: "extract" },
      { id: "s7", action: "notify", value: "Complete lesson materials ready — saved you 4 hours!" },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ── 🇮🇳 INDIA ESSENTIALS ────────────────────────────────────────

  {
    id: "irctc-tatkal-booker",
    name: "IRCTC Tatkal Booker",
    description: "Books Tatkal train tickets the moment booking opens at 10 AM. Faster than any human — never miss a seat again.",
    author: "flowos_team",
    category: "Travel",
    icon: "🚆",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: true,
    installs: 91000,
    rating: 4.5,
    reviews: 3200,
    estimatedTime: "~2 min",
    tags: ["irctc", "tatkal", "trains", "india"],
    inputs: [
      { key: "train_no", label: "Train Number", placeholder: "12951", type: "text", required: true },
      { key: "from_station", label: "From Station", placeholder: "NDLS", type: "text", required: true },
      { key: "to_station", label: "To Station", placeholder: "MMCT", type: "text", required: true },
      { key: "travel_date", label: "Travel Date", placeholder: "2026-04-15", type: "text", required: true },
      { key: "irctc_user", label: "IRCTC Username", placeholder: "your_username", type: "text", required: true, vaultKey: "irctc_username" },
      { key: "irctc_pass", label: "IRCTC Password", placeholder: "your_password", type: "password", required: true, vaultKey: "irctc_password" },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.irctc.co.in/nget/train-search" },
      { id: "s2", action: "wait", value: "2000" },
      { id: "s3", action: "ai_handle", instruction: "Login with IRCTC credentials, search for the train, select Tatkal quota, fill passenger details and complete payment." },
      { id: "s4", action: "notify", value: "Tatkal booking attempted — check your email for confirmation." },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },

  {
    id: "gst-return-filer",
    name: "GST Return Auto-Filer",
    description: "Automatically files your monthly GSTR-1 and GSTR-3B returns. Reads your sales data, calculates tax liability, and submits on the GST portal before the deadline.",
    author: "flowos_team",
    category: "Finance",
    icon: "🧾",
    version: "1.0.0",
    verified: true,
    trending: true,
    featured: false,
    installs: 42000,
    rating: 4.6,
    reviews: 1400,
    estimatedTime: "~20 min",
    tags: ["GST", "tax", "india", "compliance", "business"],
    inputs: [
      { key: "gstin", label: "GSTIN", placeholder: "27AAAAA0000A1Z5", type: "text", required: true },
      { key: "gst_username", label: "GST Portal Username", placeholder: "your_username", type: "text", required: true, vaultKey: "gst_username" },
      { key: "gst_password", label: "GST Portal Password", placeholder: "your_password", type: "password", required: true, vaultKey: "gst_password" },
      { key: "sales_data_url", label: "Sales Data (Excel/CSV link)", placeholder: "https://drive.google.com/...", type: "url", required: true },
    ],
    steps: [
      { id: "s1", action: "navigate", url: "https://www.gst.gov.in" },
      { id: "s2", action: "ai_handle", instruction: "Login with GST credentials. Navigate to Returns dashboard." },
      { id: "s3", action: "navigate", url: "{{sales_data_url}}" },
      { id: "s4", action: "ai_handle", instruction: "Read and parse the sales data. Calculate total taxable value, CGST, SGST, IGST for each HSN code." },
      { id: "s5", action: "navigate", url: "https://www.gst.gov.in/returns" },
      { id: "s6", action: "ai_handle", instruction: "Fill GSTR-1 with the sales data. Verify all figures. Submit." },
      { id: "s7", action: "notify", value: "GST return filed successfully! Acknowledgement saved." },
    ],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },

]

export function getBrainById(id: string): Brain | undefined {
  return BRAINS.find((b) => b.id === id)
}

export function getBrainsByCategory(category: string): Brain[] {
  if (category === "All") return BRAINS
  return BRAINS.filter((b) => b.category === category)
}

export function searchBrains(query: string): Brain[] {
  const q = query.toLowerCase()
  return BRAINS.filter(
    (b) =>
      b.name.toLowerCase().includes(q) ||
      b.description.toLowerCase().includes(q) ||
      b.tags.some((t) => t.includes(q))
  )
}

export function getBrainSummaries() {
  return BRAINS.map((b) => ({
    id: b.id,
    name: b.name,
    description: b.description,
  }))
}

export const BRAIN_CATEGORIES = [
  "All",
  "Research & Intelligence",
  "Business & Finance",
  "Jobs & Career",
  "Social Media",
  "Travel",
  "Finance",
  "Healthcare",
  "Legal",
  "Education",
]
